import { Html, Link, Markdown, Section, Text } from "@react-email/components";
import type * as React from "react";

interface ReportEmailTemplateProps {
	report: string;
}

export const ReportEmailTemplate: React.FC<
	Readonly<ReportEmailTemplateProps>
> = ({ report }) => (
	<Html lang="en" dir="ltr">
		<Markdown>{report}</Markdown>

		<Section>
			<Text>Report generated by Open Deep Research.</Text>
			<Link href="https://www.opendeepresearch.io">
				www.OpenDeepResearch.io
			</Link>
		</Section>
	</Html>
);
